/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v11.0
processor: MCIMX6Y2xxx05
package_id: MCIMX6Y2DVM05
mcu_data: i_mx_2_0
processor_version: 11.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "iomux_config.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'false', coreID: ca7}
- pin_list:
  - {pin_num: B3, peripheral: uSDHC1, signal: 'usdhc_data, 0', pin_signal: SD1_DATA0}
  - {pin_num: B2, peripheral: uSDHC1, signal: 'usdhc_data, 1', pin_signal: SD1_DATA1}
  - {pin_num: A2, peripheral: uSDHC1, signal: 'usdhc_data, 3', pin_signal: SD1_DATA3}
  - {pin_num: B1, peripheral: uSDHC1, signal: 'usdhc_data, 2', pin_signal: SD1_DATA2}
  - {pin_num: C2, peripheral: uSDHC1, signal: usdhc_cmd, pin_signal: SD1_CMD}
  - {pin_num: C1, peripheral: uSDHC1, signal: usdhc_clk, pin_signal: SD1_CLK}
  - {pin_num: L14, peripheral: I2C1, signal: i2c_scl, pin_signal: GPIO1_IO02}
  - {pin_num: L17, peripheral: I2C1, signal: i2c_sda, pin_signal: GPIO1_IO03}
  - {pin_num: K13, peripheral: I2C2, signal: i2c_scl, pin_signal: GPIO1_IO00}
  - {pin_num: L15, peripheral: I2C2, signal: i2c_sda, pin_signal: GPIO1_IO01}
  - {pin_num: A9, peripheral: I2C3, signal: i2c_scl, pin_signal: LCD_DATA01}
  - {pin_num: B9, peripheral: I2C3, signal: i2c_sda, pin_signal: LCD_DATA00}
  - {pin_num: D10, peripheral: I2C4, signal: i2c_scl, pin_signal: LCD_DATA03}
  - {pin_num: E10, peripheral: I2C4, signal: i2c_sda, pin_signal: LCD_DATA02}
  - {pin_num: F5, peripheral: UART6, signal: uart_rx, pin_signal: CSI_MCLK}
  - {pin_num: E5, peripheral: UART6, signal: uart_tx, pin_signal: CSI_PIXCLK}
  - {pin_num: C13, peripheral: UART7, signal: uart_rx, pin_signal: LCD_DATA16}
  - {pin_num: B13, peripheral: UART7, signal: uart_tx, pin_signal: LCD_DATA17}
  - {pin_num: C14, peripheral: UART8, signal: uart_rx, pin_signal: LCD_DATA20}
  - {pin_num: B14, peripheral: UART8, signal: uart_tx, pin_signal: LCD_DATA21}
  - {pin_num: G13, peripheral: UART5, signal: uart_rx, pin_signal: UART5_RX_DATA}
  - {pin_num: F17, peripheral: UART5, signal: uart_tx, pin_signal: UART5_TX_DATA}
  - {pin_num: G16, peripheral: UART4, signal: uart_rx, pin_signal: UART4_RX_DATA}
  - {pin_num: G17, peripheral: UART4, signal: uart_tx, pin_signal: UART4_TX_DATA}
  - {pin_num: H17, peripheral: UART3, signal: uart_tx, pin_signal: UART3_TX_DATA}
  - {pin_num: H16, peripheral: UART3, signal: uart_rx, pin_signal: UART3_RX_DATA}
  - {pin_num: J17, peripheral: UART2, signal: uart_tx, pin_signal: UART2_TX_DATA}
  - {pin_num: J16, peripheral: UART2, signal: uart_rx, pin_signal: UART2_RX_DATA}
  - {pin_num: K16, peripheral: UART1, signal: uart_rx, pin_signal: UART1_RX_DATA}
  - {pin_num: K14, peripheral: UART1, signal: uart_tx, pin_signal: UART1_TX_DATA}
  - {pin_num: D3, peripheral: uSDHC1, signal: usdhc_cd_b, pin_signal: CSI_DATA05}
  - {pin_num: E1, peripheral: ECSPI2, signal: ecspi_miso, pin_signal: CSI_DATA03}
  - {pin_num: E2, peripheral: ECSPI2, signal: ecspi_mosi, pin_signal: CSI_DATA02}
  - {pin_num: E4, peripheral: ECSPI2, signal: ecspi_sclk, pin_signal: CSI_DATA00}
  - {pin_num: E3, peripheral: ECSPI2, signal: 'ecspi_ss, 0', pin_signal: CSI_DATA01}
  - {pin_num: B16, peripheral: ECSPI1, signal: ecspi_miso, pin_signal: LCD_DATA23}
  - {pin_num: A14, peripheral: ECSPI1, signal: ecspi_mosi, pin_signal: LCD_DATA22}
  - {pin_num: C14, peripheral: ECSPI1, signal: ecspi_sclk, pin_signal: LCD_DATA20}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {                                /*!< Function assigned for the core: Cortex-A7[ca7] */
  /* There are conflicts or other incorrect settings in the configuration, the code below is generated only for 
     those registers which are set correctly and without a conflict. Open this file in Pins Tool for more details. */

  /* IOMUXC_ECSPI1_MISO_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[32U] = IOMUXC_SELECT_INPUT_DAISY(0U);
  /* IOMUXC_ECSPI1_MOSI_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[33U] = IOMUXC_SELECT_INPUT_DAISY(0U);
  /* IOMUXC_ECSPI1_SCLK_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[31U] = IOMUXC_SELECT_INPUT_DAISY(0U);
  /* IOMUXC_ECSPI2_MISO_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[36U] = IOMUXC_SELECT_INPUT_DAISY(0U);
  /* IOMUXC_ECSPI2_MOSI_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[37U] = IOMUXC_SELECT_INPUT_DAISY(1U);
  /* IOMUXC_ECSPI2_SCLK_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[35U] = IOMUXC_SELECT_INPUT_DAISY(0U);
  /* IOMUXC_ECSPI2_SS0_B_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[38U] = IOMUXC_SELECT_INPUT_DAISY(0U);
  /* IOMUXC_I2C1_SCL_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[59U] = IOMUXC_SELECT_INPUT_DAISY(0U);
  /* IOMUXC_I2C1_SDA_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[60U] = IOMUXC_SELECT_INPUT_DAISY(1U);
  /* IOMUXC_I2C2_SCL_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[61U] = IOMUXC_SELECT_INPUT_DAISY(1U);
  /* IOMUXC_I2C2_SDA_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[62U] = IOMUXC_SELECT_INPUT_DAISY(1U);
  /* IOMUXC_I2C3_SCL_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[63U] = IOMUXC_SELECT_INPUT_DAISY(2U);
  /* IOMUXC_I2C3_SDA_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[64U] = IOMUXC_SELECT_INPUT_DAISY(2U);
  /* IOMUXC_I2C4_SCL_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[65U] = IOMUXC_SELECT_INPUT_DAISY(2U);
  /* IOMUXC_I2C4_SDA_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[66U] = IOMUXC_SELECT_INPUT_DAISY(2U);
  /* IOMUXC_SW_MUX_CTL_PAD_CSI_DATA00 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[104U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(3U);
  /* IOMUXC_SW_MUX_CTL_PAD_CSI_DATA01 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[105U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(3U);
  /* IOMUXC_SW_MUX_CTL_PAD_CSI_DATA02 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[106U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(3U);
  /* IOMUXC_SW_MUX_CTL_PAD_CSI_DATA03 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[107U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(3U);
  /* IOMUXC_SW_MUX_CTL_PAD_CSI_DATA05 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[109U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(8U);
  /* IOMUXC_SW_MUX_CTL_PAD_CSI_MCLK register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[100U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(8U);
  /* IOMUXC_SW_MUX_CTL_PAD_CSI_PIXCLK register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[101U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(8U);
  /* IOMUXC_SW_MUX_CTL_PAD_GPIO1_IO00 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[6U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_GPIO1_IO01 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[7U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_GPIO1_IO02 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[8U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_GPIO1_IO03 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[9U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_LCD_DATA00 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[53U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(4U);
  /* IOMUXC_SW_MUX_CTL_PAD_LCD_DATA01 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[54U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(4U);
  /* IOMUXC_SW_MUX_CTL_PAD_LCD_DATA02 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[55U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(4U);
  /* IOMUXC_SW_MUX_CTL_PAD_LCD_DATA03 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[56U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(4U);
  /* IOMUXC_SW_MUX_CTL_PAD_LCD_DATA16 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[69U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(1U);
  /* IOMUXC_SW_MUX_CTL_PAD_LCD_DATA17 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[70U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(1U);
  /* IOMUXC_SW_MUX_CTL_PAD_LCD_DATA21 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[74U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(1U);
  /* IOMUXC_SW_MUX_CTL_PAD_LCD_DATA22 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[75U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(2U);
  /* IOMUXC_SW_MUX_CTL_PAD_LCD_DATA23 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[76U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(2U);
  /* IOMUXC_SW_MUX_CTL_PAD_SD1_CLK register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[95U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_SD1_CMD register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[94U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_SD1_DATA0 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[96U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_SD1_DATA1 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[97U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_SD1_DATA2 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[98U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_SD1_DATA3 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[99U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_UART1_RX_DATA register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[17U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_UART1_TX_DATA register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[16U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_UART2_RX_DATA register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[21U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_UART2_TX_DATA register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[20U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_UART3_RX_DATA register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[25U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_UART3_TX_DATA register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[24U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_UART4_RX_DATA register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[29U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_UART4_TX_DATA register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[28U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_UART5_RX_DATA register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[31U] = 0U;
  /* IOMUXC_SW_MUX_CTL_PAD_UART5_TX_DATA register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[30U] = 0U;
  /* IOMUXC_UART1_RX_DATA_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[91U] = IOMUXC_SELECT_INPUT_DAISY(3U);
  /* IOMUXC_UART2_RX_DATA_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[93U] = IOMUXC_SELECT_INPUT_DAISY(1U);
  /* IOMUXC_UART3_RX_DATA_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[95U] = IOMUXC_SELECT_INPUT_DAISY(1U);
  /* IOMUXC_UART4_RX_DATA_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[97U] = IOMUXC_SELECT_INPUT_DAISY(1U);
  /* IOMUXC_UART5_RX_DATA_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[99U] = IOMUXC_SELECT_INPUT_DAISY(7U);
  /* IOMUXC_UART6_RX_DATA_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[101U] = IOMUXC_SELECT_INPUT_DAISY(0U);
  /* IOMUXC_UART7_RX_DATA_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[103U] = IOMUXC_SELECT_INPUT_DAISY(2U);
  /* IOMUXC_UART8_RX_DATA_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[105U] = IOMUXC_SELECT_INPUT_DAISY(2U);
  /* IOMUXC_USDHC1_CD_B_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[108U] = IOMUXC_SELECT_INPUT_DAISY(2U);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
