/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v11.0
processor: MCIMX6Y2xxx05
package_id: MCIMX6Y2DVM05
mcu_data: i_mx_2_0
processor_version: 11.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/***********************************************************************************************************************
 * Code
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'false', coreID: ca7}
- pin_list:
  - {pin_num: B3, peripheral: uSDHC1, signal: 'usdhc_data, 0', pin_signal: SD1_DATA0}
  - {pin_num: B2, peripheral: uSDHC1, signal: 'usdhc_data, 1', pin_signal: SD1_DATA1}
  - {pin_num: A2, peripheral: uSDHC1, signal: 'usdhc_data, 3', pin_signal: SD1_DATA3}
  - {pin_num: B1, peripheral: uSDHC1, signal: 'usdhc_data, 2', pin_signal: SD1_DATA2}
  - {pin_num: C2, peripheral: uSDHC1, signal: usdhc_cmd, pin_signal: SD1_CMD}
  - {pin_num: C1, peripheral: uSDHC1, signal: usdhc_clk, pin_signal: SD1_CLK}
  - {pin_num: L14, peripheral: I2C1, signal: i2c_scl, pin_signal: GPIO1_IO02}
  - {pin_num: L17, peripheral: I2C1, signal: i2c_sda, pin_signal: GPIO1_IO03}
  - {pin_num: K13, peripheral: I2C2, signal: i2c_scl, pin_signal: GPIO1_IO00}
  - {pin_num: L15, peripheral: I2C2, signal: i2c_sda, pin_signal: GPIO1_IO01}
  - {pin_num: A9, peripheral: I2C3, signal: i2c_scl, pin_signal: LCD_DATA01}
  - {pin_num: B9, peripheral: I2C3, signal: i2c_sda, pin_signal: LCD_DATA00}
  - {pin_num: D10, peripheral: I2C4, signal: i2c_scl, pin_signal: LCD_DATA03}
  - {pin_num: E10, peripheral: I2C4, signal: i2c_sda, pin_signal: LCD_DATA02}
  - {pin_num: F5, peripheral: UART6, signal: uart_rx, pin_signal: CSI_MCLK}
  - {pin_num: E5, peripheral: UART6, signal: uart_tx, pin_signal: CSI_PIXCLK}
  - {pin_num: C13, peripheral: UART7, signal: uart_rx, pin_signal: LCD_DATA16}
  - {pin_num: B13, peripheral: UART7, signal: uart_tx, pin_signal: LCD_DATA17}
  - {pin_num: C14, peripheral: UART8, signal: uart_rx, pin_signal: LCD_DATA20}
  - {pin_num: B14, peripheral: UART8, signal: uart_tx, pin_signal: LCD_DATA21}
  - {pin_num: G13, peripheral: UART5, signal: uart_rx, pin_signal: UART5_RX_DATA}
  - {pin_num: F17, peripheral: UART5, signal: uart_tx, pin_signal: UART5_TX_DATA}
  - {pin_num: G16, peripheral: UART4, signal: uart_rx, pin_signal: UART4_RX_DATA}
  - {pin_num: G17, peripheral: UART4, signal: uart_tx, pin_signal: UART4_TX_DATA}
  - {pin_num: H17, peripheral: UART3, signal: uart_tx, pin_signal: UART3_TX_DATA}
  - {pin_num: H16, peripheral: UART3, signal: uart_rx, pin_signal: UART3_RX_DATA}
  - {pin_num: J17, peripheral: UART2, signal: uart_tx, pin_signal: UART2_TX_DATA}
  - {pin_num: J16, peripheral: UART2, signal: uart_rx, pin_signal: UART2_RX_DATA}
  - {pin_num: K16, peripheral: UART1, signal: uart_rx, pin_signal: UART1_RX_DATA}
  - {pin_num: K14, peripheral: UART1, signal: uart_tx, pin_signal: UART1_TX_DATA}
  - {pin_num: D3, peripheral: uSDHC1, signal: usdhc_cd_b, pin_signal: CSI_DATA05}
  - {pin_num: E1, peripheral: ECSPI2, signal: ecspi_miso, pin_signal: CSI_DATA03}
  - {pin_num: E2, peripheral: ECSPI2, signal: ecspi_mosi, pin_signal: CSI_DATA02}
  - {pin_num: E4, peripheral: ECSPI2, signal: ecspi_sclk, pin_signal: CSI_DATA00}
  - {pin_num: E3, peripheral: ECSPI2, signal: 'ecspi_ss, 0', pin_signal: CSI_DATA01}
  - {pin_num: B16, peripheral: ECSPI1, signal: ecspi_miso, pin_signal: LCD_DATA23}
  - {pin_num: A14, peripheral: ECSPI1, signal: ecspi_mosi, pin_signal: LCD_DATA22}
  - {pin_num: C14, peripheral: ECSPI1, signal: ecspi_sclk, pin_signal: LCD_DATA20}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {                                /*!< Function assigned for the core: Cortex-A7[ca7] */
  /* There are conflicts or other incorrect settings in the configuration, the code below is generated only for 
     those registers which are set correctly and without a conflict. Open this file in Pins Tool for more details. */

    IOMUXC_SetPinMux(IOMUXC_CSI_DATA00_ECSPI2_SCLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_CSI_DATA01_ECSPI2_SS0, 0U);
    IOMUXC_SetPinMux(IOMUXC_CSI_DATA02_ECSPI2_MOSI, 0U);
    IOMUXC_SetPinMux(IOMUXC_CSI_DATA03_ECSPI2_MISO, 0U);
    IOMUXC_SetPinMux(IOMUXC_CSI_DATA05_USDHC1_CD_B, 0U);
    IOMUXC_SetPinMux(IOMUXC_CSI_MCLK_UART6_TX, 0U);
    IOMUXC_SetPinMux(IOMUXC_CSI_PIXCLK_UART6_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO00_I2C2_SCL, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO01_I2C2_SDA, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO02_I2C1_SCL, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO03_I2C1_SDA, 0U);
    IOMUXC_SetPinMux(IOMUXC_LCD_DATA00_I2C3_SDA, 0U);
    IOMUXC_SetPinMux(IOMUXC_LCD_DATA01_I2C3_SCL, 0U);
    IOMUXC_SetPinMux(IOMUXC_LCD_DATA02_I2C4_SDA, 0U);
    IOMUXC_SetPinMux(IOMUXC_LCD_DATA03_I2C4_SCL, 0U);
    IOMUXC_SetPinMux(IOMUXC_LCD_DATA16_UART7_TX, 0U);
    IOMUXC_SetPinMux(IOMUXC_LCD_DATA17_UART7_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_LCD_DATA21_UART8_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_LCD_DATA22_ECSPI1_MOSI, 0U);
    IOMUXC_SetPinMux(IOMUXC_LCD_DATA23_ECSPI1_MISO, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_CLK_USDHC1_CLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_CMD_USDHC1_CMD, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA0_USDHC1_DATA0, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA1_USDHC1_DATA1, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA2_USDHC1_DATA2, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA3_USDHC1_DATA3, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART1_RX_DATA_UART1_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART1_TX_DATA_UART1_TX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART2_RX_DATA_UART2_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART2_TX_DATA_UART2_TX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART3_RX_DATA_UART3_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART3_TX_DATA_UART3_TX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART4_RX_DATA_UART4_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART4_TX_DATA_UART4_TX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART5_RX_DATA_UART5_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART5_TX_DATA_UART5_TX, 0U);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
